site_name: 2024.1-UnB-TV-DOC

repo_name: '2024.1-UnB-TV-DOC'
repo_url: 'https://github.com/fga-eps-mds/2024.1-UnB-TV-DOC'

nav:
  - Home: index.md
  - Guia de Contribuição:
    - Código de Conduta: contribuicao/CodigoConduta.md
    - Políticas de Contribuição: contribuicao/PoliticasContribuicao.md
  - Treinamentos:
    - Quadro de Conhecimentos: treinamentos/QuadroConhecimento.md
  - Planejamento:
    - Plano de Tempo: planejamento/PlanejamentoTempo.md
    - Plano de Comunicação: planejamento/PlanoComunicacao.md
    # - Metodologias: planejamento/Metodologias.md
  - Sprints:
    - Sprint Template: sprints/SprintTemplate/SprintTemplate.md
    - Pareamento Template: sprints/SprintTemplate/PareamentoTemplate.md
  - Atas de Reuniões:  
    - Reunião 1: atasReuniao/reuniao1.md
    - Reunião 2: atasReuniao/reuniao2.md
    - Reunião 3: atasReuniao/reuniao3.md

theme:
  name: material
  language: 'pt'
  logo: assets/unbtv-icon.ico
  favicon: assets/unbtv-icon.ico
  palette:
    primary: blue green
