site_name: 2024.1-UnB-TV-DOC

repo_name: '2024.1-UnB-TV-DOC'
repo_url: 'https://github.com/fga-eps-mds/2024.1-UnB-TV-DOC'

nav:
  - Home: index.md
  - Guia de Contribuição:
    - Código de Conduta: contribuicao/CodigoConduta.md
    - Políticas de Contribuição: contribuicao/PoliticasContribuicao.md
  - Treinamentos:
    - Quadro de Conhecimentos: treinamentos/QuadroConhecimento.md
    - Dojo Inicial: treinamentos/dojoInicial.md
    - Dojo Git: treinamentos/dojoGit.md
    - Dojo BackEnd: treinamentos/DojoBack.md
  - Código Fonte:
    - Documentação dos Endpoints: codigo/endpoints.md
    - Rodar o Projeto Local (Docker): codigo/rodarprojeto.md
  - Planejamento:
    - Plano de Tempo: planejamento/PlanejamentoTempo.md
    - Plano de Comunicação: planejamento/PlanoComunicacao.md
    - Plano de Custos: planejamento/planocusto.md
    - Plano de Qualidade: planejamento/PlanoQualidade.md
    - Metodologias: planejamento/Metodologias.md
  - Produto:
    - Lean Inception: produto/leaninception.md
    - Product Backlog: produto/backlog.md
  - Sprints:
    - Sprint Template: sprints/SprintTemplate/SprintTemplate.md
    - Pareamento Template: sprints/SprintTemplate/PareamentoTemplate.md
  - Atas de Reuniões:
    - Reuniões da Equipe:
      - Reunião 1: atasReuniao/reuniao1.md
      - Reunião 2: atasReuniao/reuniao2.md
      - Reunião 3: atasReuniao/reuniao3.md
    - Reuniões com os Stakeholders:
      - Reunião 4: atasReuniao/reuniao4.md
      - Reunião 5: atasReuniao/reuniao5.md
      - Reunião 6: atasReuniao/reuniao6.md

theme:
  name: material
  language: 'pt'
  logo: assets/unbtv-icon.ico
  favicon: assets/unbtv-icon.ico
  palette:
    primary: blue green
