site_name: 2024.1-UnB-TV-DOC

repo_name: '2024.1-UnB-TV-DOC'
repo_url: 'https://github.com/fga-eps-mds/2024.1-UnB-TV-DOC'

nav:
  - Home: index.md
  - Guia de Contribuição:
    - Políticas de Contribuição: contribuicao/PoliticasContribuicao.md
  - Planejamento:
    - Plano de Comunicação: planejamento/PlanoComunicacao.md

theme:
  name: material
  language: 'pt'
  logo: assets/unbtv-icon.ico
  favicon: assets/unbtv-icon.ico
  palette:
    primary: blue green