site_name: 2024.1-UnB-TV-DOC

repo_name: '2024.1-UnB-TV-DOC'
repo_url: 'https://github.com/fga-eps-mds/2024.1-UnB-TV-DOC'

nav:
  - Home: index.md
  - Guia de Contribuição:
    - Código de Conduta: contribuicao/CodigoConduta.md
    - Políticas de Contribuição: contribuicao/PoliticasContribuicao.md
  - Treinamentos:
    - Quadro de Conhecimentos: treinamentos/QuadroConhecimento.md
    - Dojo Inicial: treinamentos/dojoInicial.md
    - Dojo Git: treinamentos/dojoGit.md
    - Dojo BackEnd: treinamentos/DojoBack.md
    - Dojo FrontEnd: treinamentos/dojoFront.md
    - Dojo Full Stack: treinamentos/dojoFullStack.md
  - Código Fonte:
    - Documentação dos Endpoints: codigo/endpoints.md
    - Arquitetura do projeto: codigo/arquitetura.md
    - Rodar o Projeto Local (Docker): codigo/rodarprojeto.md
    - Guia de Estilo: codigo/guia_de_estilo.md
  - Planejamento:
    #- Plano de Tempo: planejamento/PlanejamentoTempo.md
    - Plano de Comunicação: planejamento/PlanoComunicacao.md
    - Plano de Custos: planejamento/planocusto.md
    - Plano de Qualidade: planejamento/PlanoQualidade.md
    - Plano de Riscos: planejamento/PlanoRiscos.md
    - Plano de Aceitação: planejamento/PlanoAceitacao.md    
    - Metodologias: planejamento/Metodologias.md
    - EVM: planejamento/evm.md
  - Produto:
    - Lean Inception: produto/leaninception.md
    #- Product Backlog: produto/backlog.md
    - Estrutura Analítica do Projeto (EAP): produto/eap.md
  - Sprints:
    - Sprint Template: sprints/SprintTemplate/SprintTemplate.md
    - Sprint 1: sprints/Sprint1.md
    - Sprint 2: sprints/Sprint2.md
    - Sprint 3: sprints/Sprint3.md
    - Sprint 4: sprints/Sprint4.md
    - Sprint 5: sprints/Sprint5.md
    - Sprint 6: sprints/Sprint6.md
    - Sprint 7: sprints/Sprint7.md
    - Sprint 8: sprints/Sprint8.md
  - Atas de Reuniões:
    - Reuniões da Equipe:
      - Pontapé Inicial: atasReuniao/reuniao1.md
      - Ata Dojo Infra e Dev: atasReuniao/reuniao2.md
      - Apresentação Lean Inception p/ MDS: atasReuniao/reuniao3.md
      - Definição Story Points: atasReuniao/reuniao7.md
      - Desenvolvimento 1ª US (US03): atasReuniao/reuniao9.md
      - Planning Sprint 2: atasReuniao/reuniao11.md
      - Planning Sprint 3: atasReuniao/reuniao12.md
      - Retrospectiva Sprint 3: atasReuniao/reuniao14.md
      - Planning Sprint 4: atasReuniao/reuniao16.md
      - Retrospectiva Sprint 4: atasReuniao/reuniao17.md
      - Planning Sprint 5: atasReuniao/reuniao19.md
      - Overview Novos Integrantes: atasReuniao/reuniao20.md
      - Retrospectiva Sprint 5: atasReuniao/reuniao21.md
      - Planning Sprint 6: atasReuniao/reuniao23.md
      - Retrospectiva Sprint 6: atasReuniao/reuniao24.md
      - Planning Sprint 7: atasReuniao/reuniao26.md
      - Retrospectiva Sprint 7: atasReuniao/reuniao27.md
      - Planning Sprint 8: atasReuniao/reuniao29.md   
    - Reuniões com os Stakeholders:
      - Kick-off projeto: atasReuniao/reuniao4.md
      - Desenvolvimento MVP PT1: atasReuniao/reuniao5.md
      - Desenvolvimento MVP PT2: atasReuniao/reuniao6.md
      - Reunião com o PO para Início do Desenvolvimento: atasReuniao/reuniao8.md
      - Review Sprint 1: atasReuniao/reuniao10.md
      - Entrega Release 1 + Review Sprint 2: atasReuniao/reuniao13.md
      - Review Sprint 3: atasReuniao/reuniao15.md
      - Entrega Release 2 + Review Sprint 4: atasReuniao/reuniao18.md
      - Review Sprint 5: atasReuniao/reuniao22.md
      - Review Sprint 6: atasReuniao/reuniao25.md
      - Entrega MVP (Release 3) + Review Sprint 7: atasReuniao/reuniao28.md
  - Metodologia de Comportamento do Projeto:
      - Qualidade de Software do Projeto: eps_metodologia/qualidade.md
      - Uso do PMBOK para Gerenciamento: eps_metodologia/usoPMBOK.md
      - Interação EPS/MDS no Projeto: eps_metodologia/controleProjeto.md

theme:
  name: material
  language: 'pt'
  logo: assets/unbtv-icon.ico
  favicon: assets/unbtv-icon.ico
  palette:
    primary: blue green
