site_name: 2024.1-UnB-TV-DOC

repo_name: '2024.1-UnB-TV-DOC'
repo_url: 'https://github.com/fga-eps-mds/2024.1-UnB-TV-DOC'

nav:
  - Home: index.md
  - Guia de Contribuição:
    - Código de Conduta: contribuicao/CodigoConduta.md
    - Políticas de Contribuição: contribuicao/PoliticasContribuicao.md
  - Treinamentos:
    - Quadro de Conhecimentos: treinamentos/QuadroConhecimento.md
    - Dojo Inicial: treinamentos/dojoInicial.md
    - Dojo Git: treinamentos/dojoGit.md
    - Dojo BackEnd: treinamentos/DojoBack.md
    - Dojo FrontEnd: treinamentos/dojoFront.md
    - Dojo Full Stack: treinamentos/dojoFullStack.md
  - Código Fonte:
    - Documentação dos Endpoints: codigo/endpoints.md
    - Arquitetura do projeto: codigo/arquitetura.md
    - Rodar o Projeto Local (Docker): codigo/rodarprojeto.md
  - Planejamento:
    #- Plano de Tempo: planejamento/PlanejamentoTempo.md
    - Plano de Comunicação: planejamento/PlanoComunicacao.md
    - Plano de Custos: planejamento/planocusto.md
    - Plano de Qualidade: planejamento/PlanoQualidade.md
    - Plano de Riscos: planejamento/PlanoRiscos.md
    - Metodologias: planejamento/Metodologias.md
  - Produto:
    - Lean Inception: produto/leaninception.md
    #- Product Backlog: produto/backlog.md
    - Estrutura Analítica do Projeto (EAP): produto/eap.md
  - Sprints:
    - Sprint Template: sprints/SprintTemplate/SprintTemplate.md
    - Sprint 1: sprints/Sprint1.md
    - Sprint 2: sprints/Sprint2.md
  - Atas de Reuniões:
    - Reuniões da Equipe:
      - Reunião 1: atasReuniao/reuniao1.md
      - Reunião 2: atasReuniao/reuniao2.md
      - Reunião 3: atasReuniao/reuniao3.md
      - Reunião 7: atasReuniao/reuniao7.md
      - Reunião 9: atasReuniao/reuniao9.md
      - Reunião 11: atasReuniao/reuniao11.md
      - Reunião 12: atasReuniao/reuniao12.md
    - Reuniões com os Stakeholders:
      - Reunião 4: atasReuniao/reuniao4.md
      - Reunião 5: atasReuniao/reuniao5.md
      - Reunião 6: atasReuniao/reuniao6.md
      - Reunião 8: atasReuniao/reuniao8.md
      - Reunião 10: atasReuniao/reuniao10.md
      - Reunião 13: atasReuniao/reuniao13.md

theme:
  name: material
  language: 'pt'
  logo: assets/unbtv-icon.ico
  favicon: assets/unbtv-icon.ico
  palette:
    primary: blue green
