site_name: 2024.1-UnB-TV-DOC

repo_name: '2024.1-UnB-TV-DOC'
repo_url: 'https://github.com/fga-eps-mds/2024.1-UnB-TV-DOC'

nav:
  - Home: index.md
  - Planejamento:
    - Quadro de Horários: planejamento/quadro_horarios.md

theme: readthedocs